#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc !== 1) {
	fprintf(STDERR, "Usage: %s < foo.pgn\n", $argv[0]);
	die(1);
}

$buf = '';

while($next = fread(STDIN, 8192)) {
	if($next === false) break;
	$buf .= $next;

	while(($p = strpos($buf, "\n[Event ")) !== false) {
		echo json_encode(substr($buf, 0, $p + 1)), "\n";
		$buf = substr($buf, $p + 1);
	}
}

if($buf !== '') echo json_encode($buf), "\n";
