#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc !== 2) {
	fprintf(STDERR, "Usage: %s <prefix>\n", $argv[0]);
	die(1);
}

function depth(?array $puzzle, &$min, &$max): void {
	if($puzzle === null) {
		$min = $max = 0;
		return;
	}

	$min = PHP_INT_MAX;
	$max = -$min;

	foreach($puzzle as $next) {
		depth($next[1] ?? null, $nextmin, $nextmax);
		if($nextmin + 1 < $min) $min = $nextmin + 1;
		if($nextmax + 1 > $max) $max = $nextmax + 1;
	}
}

function write_puzzle(array $puz, string $tag): void {
	static $files = [];

	if(!isset($files[$tag])) {
		$files[$tag] = fopen($tag, 'ab');
	}

	fputs($files[$tag], json_encode($puz)."\n");
}

while(($line = fgets(STDIN)) !== false) {
	$puz = json_decode($line, true);
	assert(is_array($puz));

	depth($puz[2], $mindepth, $maxdepth);
	write_puzzle($puz, $argv[1].'d'.$maxdepth.'.jl');
}
