image: alpine:edge

before_script:
- echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
- apk add --no-cache coreutils bash make wget git gzip sassc
- git submodule update --recursive --init

pages:
    stage: deploy
    script:
    - make all-frontend
    - cp -R frontend public
    - find public/puzzles -name "*.json" -delete
    - rm -R public/index.xhtml
    - mv public/stockfish.wasm public/stockfish.wasm2.js
    - sed -i -e s/SF_VERSION/$(b2sum public/stockfish.wasm2.js | cut -d' ' -f1)/ -e s/\"stockfish.wasm\"/\"stockfish.wasm2.js\"/ public/stockfish.wasm.js
    - find public -type f -exec gzip --best --keep '{}' ';'
    artifacts:
        paths:
        - public
    only:
    - master
