image: alpine:edge

before_script:
- echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
- apk add --no-cache coreutils bash make wget git gzip php7 build-base cmake clang sassc
- git submodule update --recursive --init

pages:
    stage: deploy
    script:
    - make all-frontend
    - cp -R frontend public
    - find public/puzzles -name "*.json" -delete
    - rm -R public/index.xhtml
    - find public -type f -name "*.js" -o -name "*.html" -o -name "*.css" -exec gzip --best --keep '{}' ';'
    artifacts:
        paths:
        - public
    only:
    - master
