image: php:alpine

before_script:
- apk add --no-cache coreutils make wget

pages:
    stage: deploy
    script:
    - make
    - cp -R frontend public
    - find public -type f -exec gzip --best --keep '{}' ';'
    artifacts:
        paths:
        - public
    only:
    - master
