image: alpine:edge

before_script:
- echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
- apk add --no-cache coreutils make wget git gzip php7 build-base cmake clang emscripten sassc
- git submodule update --recursive --init

pages:
    stage: deploy
    script:
    - make
    - cp -R frontend public
    - find public/puzzles -name "*.json" -delete
    - rm -R public/index.xhtml public/js
    - find public -type f -exec gzip --best --keep '{}' ';'
    artifacts:
        paths:
        - public
    only:
    - master
