#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

require __DIR__.'/../../tools/ormulogun.php';

/* XXX: as args maybe? */

/* For ranges, the lower bound is always inclusive and the upper bound
 * is always exclusive. */

const LOWER_RATING_RANGE = [ 1800, PHP_INT_MAX ];
const HIGHER_RATING_RANGE = [ 2000, PHP_INT_MAX ];
const TIME_RANGE = [ 600, PHP_INT_MAX ];
const INCREMENT_FACTOR = 40;
const EVENT_FILTER = '%^Rated %';



if($argc !== 1) {
	fprintf(STDERR, "Usage: %s < chunked-pgn...", $argv[0]);
	die(1);
}

while($pgn = fgets(STDIN)) {
	$tags = orm_parse_pgn(json_decode($pgn));

	if(!isset($tags['Moves']) || $tags['Moves'] === []) continue;
	if(!isset($tags['Event']) || !isset($tags['WhiteElo']) || !isset($tags['BlackElo']) || !isset($tags['TimeControl'])) continue;

	$lower = min((int)$tags['WhiteElo'], (int)$tags['BlackElo']);
	if($lower < LOWER_RATING_RANGE[0] || $lower >= LOWER_RATING_RANGE[1]) continue;

	$upper = max((int)$tags['WhiteElo'], (int)$tags['BlackElo']);
	if($upper < HIGHER_RATING_RANGE[0] || $upper >= HIGHER_RATING_RANGE[1]) continue;

	if(!preg_match(EVENT_FILTER, $tags['Event'])) continue;

	if(!preg_match('%^(?<base>[0-9]+)\+(?<inc>[0-9]+)$%', $tags['TimeControl'], $tc)) continue;
	$time = (int)$tc['base'] + INCREMENT_FACTOR * (int)$tc['inc'];
	if($time < TIME_RANGE[0] || $time >= TIME_RANGE[1]) continue;

	echo json_encode($tags['Moves']), "\n";
}
