#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* XXX: as args maybe? */
const RATING_CUTOFF = 2000;
const TIME_CUTOFF = 900;

if($argc === 1) {
	fprintf(STDERR, "Usage: %s <pgn1> <pgn2> <pgn3>...\n", $argv[0]);
	die(1);
}

array_shift($argv);

foreach($argv as $pgn) {
	$pgn = json_decode($pgn);
	$tags = [];

	preg_match_all('%^\[(?<k>[A-Z][A-Za-z]*) "(?<v>[^"]*)"\]$%m', $pgn, $match, PREG_SET_ORDER);
	foreach($match as $m) {
		$tags[$m['k']] = $m['v'];
	}

	if(!isset($tags['WhiteElo']) || (int)$tags['WhiteElo'] < RATING_CUTOFF) continue;
	if(!isset($tags['BlackElo']) || (int)$tags['BlackElo'] < RATING_CUTOFF) continue;
	if(!isset($tags['TimeControl']) || !preg_match('%^(?<base>[0-9]+)\+(?<inc>[0-9]+)$%', $tags['TimeControl'], $tc)) continue;
	if((int)$tc['base'] + 40 * (int)$tc['inc'] < TIME_CUTOFF) continue;

	if(!preg_match('%^1\. (?<moves>.+)$%m', $pgn, $match)) continue;
	echo $match[0], "\n";
}
