#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc !== 3) {
	fprintf(STDERR, "Usage: %s <jl-1> <jl-2>\n", $argv[0]);
	die(1);
}

function canonicalize_fen(string $fen): string {
	/* XXX */
	$parts = explode(' ', $fen, 5);
	array_pop($parts);
	return implode(' ', $parts);
}

$f = fopen($argv[1], 'rb');
$i = 0;
$puzzles = [];
$index = [];

while(($line = fgets($f)) !== false) {
	$p = json_decode($line, true);
	$k = canonicalize_fen($p[0]);

	assert(!isset($index[$k]));
	$index[$k] = $i;
	$puzzles[] = $p;
	++$i;
}

fclose($f);
$f = fopen($argv[2], 'rb');
while(($line = fgets($f)) !== false) {
	$p = json_decode($line, true);
	$k = canonicalize_fen($p[0]);

	if(isset($index[$k])) {
		$puzzles[$index[$k]] = $p;
	} else {
		$index[$k] = $i;
		$puzzles[] = $p;
		++$i;
	}
}

foreach($puzzles as $p) {
	echo json_encode($p), "\n";
}
