#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$failures = 0;

while($puzjson = fgets(STDIN)) {
	$puzjson = substr($puzjson, 0, -1);

	/* XXX: use proc_open() */
	$retagged = json_decode(shell_exec('echo '.escapeshellarg($puzjson).' | retag-puzzles'));
	$puz = json_decode($puzjson);

	if(!is_array($retagged)) {
		printf("Test failed: %s --> could not retag\n", $puzjson);
		++$failures;
		continue;
	}

	sort($puz[2]);
	sort($retagged[2]);
	$epuz = json_encode($puz, JSON_UNESCAPED_SLASHES);
	$eretagged = json_encode($retagged, JSON_UNESCAPED_SLASHES);

	if($epuz !== $eretagged) {
		$diff = '';
		$ptags = array_flip($puz[2]);
		$prtags = array_flip($retagged[2]);
		foreach($ptags as $k => $v) {
			if(!isset($prtags[$k])) {
				$diff .= sprintf(' %c[31m-%s%c[0m', 27, $k, 27);
			}
		}
		foreach($prtags as $k => $v) {
			if(!isset($ptags[$k])) {
				$diff .= sprintf(' %c[32m+%s%c[0m', 27, $k, 27);
			}
		}

		printf("%c[1mTest failed:%c[0m %s -->%s\n", 27, 27, $puzjson, $diff);
		++$failures;
		continue;
	}

	printf("Test OK: %s\n", $puzjson);
}

die($failures);
