#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc !== 2) {
	fprintf(STDERR, "Usage: %s <manifest.json>\n", $argv[0]);
	die(1);
}

$manifest = file_exists($argv[1]) ? json_decode(file_get_contents($argv[1]), true) : [];
$index = [];

foreach($manifest as $k => $v) {
	assert(isset($v['src']));
	$index[$v['src']] = $k;
}

$oldcwd = getcwd();
chdir(pathinfo($argv[1], PATHINFO_DIRNAME));
$me = pathinfo($argv[1], PATHINFO_BASENAME);
foreach(glob('*.json') as $f) {
	if($f === $me) continue;
	$puzzles = json_decode(file_get_contents($f));
	$tc = [];

	foreach($puzzles as $p) {
		foreach($p[2] as $tag) {
			$tc[$tag] = ($tc[$tag] ?? 0) + 1;
		}
	}

	if(isset($index[$f])) {
		$manifest[$index[$f]]['count'] = count($puzzles);
		$manifest[$index[$f]]['tags'] = $tc;
		continue;
	}

	$manifest[] = [
		'id' => $id = pathinfo($f, PATHINFO_FILENAME),
		'src' => $f,
		'count' => count($puzzles),
		'name' => ucfirst($id),
		'desc' => 'Auto-generated description.',
		'tags' => $tc,
	];
}

chdir($oldcwd);
file_put_contents($argv[1], json_encode($manifest, JSON_PRETTY_PRINT));
