#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

array_shift($argv);
foreach($argv as $testjson) {
	$test = json_decode($testjson, true);

	/* XXX: this is highly non deterministic */
	$puzjson = trim(shell_exec(sprintf(
		'%s --uci-engine-limiter-probe "depth 12" --uci-engine-limiter "depth 23" %s --max-puzzles 1 %s',
		escapeshellcmd(__DIR__.'/../tools/gen-puzzles'),
		$test[0],
		escapeshellarg(json_encode($test[2]))
	)));

	if($puzjson === '') {
		fprintf(STDERR, "Unexpected lack of puzzle!\nTest: %s\n", $testjson);
		die(1);
	}

	$puz = json_decode($puzjson, true);
	foreach($test[1] as $wanttag) {
		if(!in_array($wanttag, $puz[2], true)) {
			fprintf(STDERR, "Puzzle is lacking tag: '%s'\nTest: %s\nPuzzle: %s\n", $wanttag, $testjson, $puzjson);
			die(1);
		}
	}

	foreach($puz[2] as $tag) {
		if(!in_array($tag, $test[1], true)) {
			fprintf(STDERR, "Puzzle has extra tag: '%s'\nTest: %s\nPuzzle: %s\n", $tag, $testjson, $puzjson);
			die(1);
		}
	}

	printf("Test OK: %s\n", $testjson);
}
