#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc < 5) {
	fprintf(STDERR, "Usage: %s <batch-size> <prune-threshold> out.tsv.zst in1.tsd.zst in2.tsd.zst...>\n", $argv[0]);
	die(1);
}

array_shift($argv);
$bsize = (int)array_shift($argv);
$thresh = (int)array_shift($argv);
$out = array_shift($argv);

$tmproot = 'tmp.'.getmypid().'.'.microtime(true).'.';
$gen = 0;
$tomerge = $argv;

while(count($tomerge) > 1) {
	assert(mkdir($tmp = $tmproot.$gen));

	$cmd = 'zstdize merge-books '.(count($tomerge) > $bsize ? 0 : $thresh).' --';
	if(count($tomerge) > $bsize) {
		$cmd = 'parallel -N'.$bsize.' --files --compress --compress-program pzstd --tmpdir '.escapeshellarg($tmp).' '.$cmd.' :::';
	}

	$inputs = '';
	foreach($tomerge as $f) {
		$inputs .= ' '.escapeshellarg($f);
	}

	passthru($cmd.$inputs.' >/dev/null', $ret);
	if($ret !== 0) die($ret);

	if($gen > 0) {
		passthru('rm -f '.$inputs);
	}
	$tomerge = glob($tmp.'/par*.par');
	++$gen;
}

assert(count($tomerge) === 1);
if($gen > 0) {
	rename($tomerge[0], $out);
} else {
	copy($tomerge[0], $out);
}

passthru('find . -mindepth 1 -maxdepth 1 -type d -name '.escapeshellarg($tmproot.'*').' -exec rmdir {} +');
