#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$rows = [];

while($line = fgets(STDIN)) {
	list($eco, $opening, $variation, $pos, $age, $count) = explode("\t", substr($line, 0, - 1));

	$a = [ $eco, $opening, $variation, (int)$age, (int)$count ];

	if($count < 10) {
		fprintf(STDERR, "Not enough data on opening: %s\n", json_encode($a));
		continue;
	}


	if(!isset($rows[$pos])) {
		$rows[$pos] = $a;
		continue;
	}

	fprintf(STDERR, "Conflict for position %s\n%s\n%s\n", $pos, json_encode($rows[$pos]), json_encode($a));

	if($rows[$pos][4] < $a[4]) {
		$rows[$pos] = $a;
	}
}

uasort($rows, function(array $a, array $b) {
	return strcmp($a[0], $b[0]) ?: (strcmp($a[1], $b[1]) ?: strcmp($a[2], $b[2]));
});

foreach($rows as $pos => list($eco, $op, $var)) {
	printf("%s\t%s\t%s\t%s\n", $eco, $op, $var, $pos);
}
