#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc < 3) {
	fprintf(STDERR, "Usage: %s <prune-threshold> in1.tsd in2.tsd...\n", $argv[0]);
	die(1);
}

const CHUNK_SIZE = 4;

array_shift($argv);
$prune = (int)array_shift($argv);
$out = array_shift($argv);

$tomerge = array_map('escapeshellarg', $argv);

while(count($tomerge) > CHUNK_SIZE) {
	$merged = [];

	foreach(array_chunk($tomerge, CHUNK_SIZE) as $chunk) {
		$merged[] = '<(merge-books 0 '.implode(' ', $chunk).')';
	}

	$tomerge = $merged;
}

$cmd = 'merge-books '.$prune.' '.implode(' ', $tomerge);
passthru('bash -c '.escapeshellarg($cmd), $ret);
die($ret);
