#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$bestcount = 0;
$bestage = 0;
$bestposition = null;

$curopening = null;
$curposition = null;
$curcount = 0;
$curage = PHP_INT_MAX;

while(true) {
	$line = fgets(STDIN);

	if($line !== false) {
		list($count, , , $code, $opening, $variation, $position, $age) = explode("\t", substr($line, 0, -1));
		$opening = sprintf("%s\t%s\t%s", $code, $opening, $variation);
		$count = (int)$count;
		$age = (int)$age;
	}

	/* EOF, or moving to another opening */
	if($line === false || $curopening !== $opening) {
		if($bestposition !== null) {
			printf("%s\t%s\t%d\t%d\n", $curopening, $bestposition, $bestage, $bestcount);
		}

		if($line === false) break;

		$curopening = $opening;
		$bestposition = null;
		$bestcount = 0;
		$bestage = 0;
	}

	/* Same opening, moving to another position */
	if($curposition !== $position) {
		if($curcount > $bestcount || ($curcount === $bestcount && $curage > $bestage)) {
			/* New best */
			$bestcount = $curcount;
			$bestage = $curage;
			$bestposition = $curposition;
		}

		$curposition = $position;
		$curcount = $count;
		$curage = $age;
	} else {
		/* Same opening, same position */
		$curcount += $count;
		$curage = min($curage, $age);
	}
}
