#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

ini_set('memory_limit', -1);
assert_options(ASSERT_BAIL, 1);

$rows = [];

while($f = fgets(STDIN)) {
	list($code, $opening, $variation, $position, $age, $count) = explode("\t", substr($f, 0, -1));
	$k = sprintf("%s\t%s\t%s", $code, $opening, $variation);
	$rows[$k][$position] = [ $age, $count ];
}

while($rows !== []) {
	$minage = PHP_INT_MAX;
	$maxcount = 0;
	$ck = null;
	$cp = null;

	foreach($rows as $k => &$a) {
		list($age, $count) = reset($a);
		$position = key($a);

		if($age > $minage) continue;
		if($age === $minage && $count < $maxcount) continue;

		$minage = $age;
		$maxcount = $count;
		$ck = $k;
		$cp = $position;
	}

	printf("%s\t%s\n", $ck, $cp);

	unset($rows[$ck]);
	foreach($rows as $k => &$a) {
		unset($rows[$k][$cp]);
		if($rows[$k] === []) {
			unset($rows[$k]);
		}
	}
}
