#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc !== 1) {
	fprintf(STDERR, "Usage: %s < input.tsv\n", $argv[0]);
	die(1);
}

$prevline = null;
$prevpos = null;
$prevlan = null;

while(true) {
	$line = fgets(STDIN);

	if($line !== false) {
		list(, , , $pos, $lan) = explode("\t", substr($line, 0, -1));
	}

	/* EOF, or moving to another position */
	if($line === false || $pos !== $prevpos) {
		if($prevpos !== null && $prevlan !== '') {
			echo $prevline;
		}

		if($line === false) break;
	} else {
		/* Same position */
		echo $prevline;
	}

	$prevline = $line;
	$prevpos = $pos;
	$prevlan = $lan;
}
