#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc === 1) {
	fprintf(STDERR, "Usage: %s command arg1 arg2... -- arg3.zstd arg4.zstd...\n", $argv[0]);
	die(1);
}

array_shift($argv);
$command = null;
$pre = true;
while($argv !== []) {
	$a = array_shift($argv);

	if($command === null) {
		$command = escapeshellcmd($a);
		continue;
	}

	if($a === '--') {
		$pre = false;
		continue;
	}

	if($pre) {
		$command .= ' '.escapeshellarg($a);
	} else {
		$command .= ' <(zstdcat '.escapeshellarg($a).')';
	}
}

$command = 'bash -c '.escapeshellarg($command);
passthru($command, $ret);
die($ret);
