#!/usr/bin/env php
<?php
/* Copyright 2018 Romain "Artefact2" Dal Maso <artefact2@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

if($argc !== 1) {
	fprintf(STDERR, "Usage: %s < foo.pgn\n", $argv[0]);
	die(1);
}

function encode_json_string(string $s): string {
	return '"'.str_replace(
		[ '\\', '"', "\b", "\f", "\n", "\r", "\t" ],
		[ '\\\\', '\\"', '\\b', '\\f', '\\n', '\\r', '\\t' ],
		$s
	).'"';
}

$buf = '';

while(!feof(STDIN)) {
	$buf .= fread(STDIN, 32768);

	while(($p = strpos($buf, "\n\n[")) !== false) {
		$pgn = substr($buf, 0, $p + 2);
		echo encode_json_string($pgn), "\n";
		$buf = substr($buf, $p + 2);
	}
}

if($buf !== '') echo encode_json_string($buf), "\n";
